CREATE TABLE OPERATION
  (
  id BIGINT NOT NULL AUTO_INCREMENT,
  ts TIMESTAMP NOT NULL, --TODO как сделать значение по умолчанию CURRENT_TIMESTAMP в timezone=UTC ?
  state ENUM('NEW', 'WORKING', 'PROCESSED', 'ERROR') DEFAULT 'NEW',
  PRIMARY KEY (id)
  );

CREATE SEQUENCE OPERATION_ID_SEQ
  MINVALUE 1
  MAXVALUE 9999999999999999
  START WITH 1
  INCREMENT BY 100
  CACHE 100;
